[feat] Model dependencies and local training
odahu/odahu-trainer pull request #15
Opened 2020-03-01 19:57 UTC by mcdoker18

2020-03-03 12:59 UTC, maxkochubey approved these changes

2020-03-03 15:22 UTC, karbyshevds requested changes

2020-03-03 15:22 UTC, karbyshevds commented on mlflow/README.md
> +Odahu-flow's toolchain for MLFlow is responsible for running process of training MLFlow models. It produces model as ZIP archive in Legion's General Python Prediction Interface.
```suggestion
Odahu-flow's toolchain for MLFlow is responsible for running process of training MLFlow models. It produces model as ZIP archive in Odahu's General Python Prediction Interface.
```

2020-03-04 07:34 UTC, mcdoker18 commented on mlflow/README.md
> +Odahu-flow's toolchain for MLFlow is responsible for running process of training MLFlow models. It produces model as ZIP archive in Legion's General Python Prediction Interface.
Fixed

2020-03-04 17:22 UTC, vlad-tokarev approved these changes

2020-03-04 21:38 UTC, merged